# Generated by Django 4.2.4 on 2023-09-25 13:09

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal', models.CharField(max_length=100)),
                ('breeds', models.CharField(max_length=800)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('uuid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Unnamed', max_length=150)),
                ('animal', models.CharField(default='', max_length=150)),
                ('breed', models.CharField(default='', max_length=150)),
                ('location', models.CharField(blank=True, max_length=150, null=True)),
                ('image', models.ImageField(blank=True, default='images/pet.png', null=True, upload_to='images/')),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('info', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PetAttachmentImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/pet_attachments_images/')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet', to='api.pet')),
            ],
        ),
    ]
